[package]
name = "geogebra-types"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.210", features = ["derive"] }
quick-xml = { version = "0.36.1", features = ["serialize"] }
